waitingLoc:
  world: "world"
  x: -29
  y: 63
  z: 181

mapLoc:
  world: "world"
  x: -24
  y: 64
  z: 189

minimumToStart: 10

timeTillPvP: 1200

worm-head-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZGYwM2FkOTYwOTJmM2Y3ODk5MDI0MzY3MDljZGY2OWRlNmI3MjdjMTIxYjNjMmRhZWY5ZmZhMWNjYWVkMTg2YyJ9fX0="
worm-segment-texture: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2I0MzU0MTUxN2RkYTE4NjliOGMzOTBlZDRmZTViNWRmMjc4OTYxMDhlNDY2ZjAwYzE4NTdkZTdmNDJiMGUwZSJ9fX0="